### ISSUE TITLE
GitHub Page link should be moved

### ISSUE THREAD

**Issue by eggplants** [duyet/bruteforce-database#45]
You changed your username. (from `duyetdev` to `duyet`)
So this repo's site link of GitHub pages should be moved `http://duyetdev.github.io/bruteforce-database` to `https://duyet.github.io/bruteforce-database`.
![image](https://user-images.githubusercontent.com/42153744/91432119-3c27b980-e89c-11ea-815f-eb5936471245.png)

**Comment by duyet** [comment]
Updated, thank you :D
